title: Nathan Denny
logo: /assets/headshot.png
description: ndenny@iastate.edu - 847.505.6045
#show_downloads: false
theme: jekyll-theme-minimal
header_pages:
  - Home: /
  - Projects: /projects/
  - Contact Me: /contact/
  - Classes: /classes/
  - Onyx: /onyx/
